name: Test CI

on:
  # Triggers the workflow on push and pull request events but only for pull_requests on the main branch
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies using pip
        run: pip install -e ".[dev]"

      - name: Checking static types using mypy
        run: mypy --strict ocrdbrowser ocrdmonitor

      - name: Testing using pytest
        run: |
          pip install pytest-clarity # coloured diff output
          pytest tests -m "not integration"
